vim.keymap.set("n", "gr", function() vim.lsp.buf.references() end)
vim.keymap.set("n", "gi", function() vim.lsp.buf.implementation() end)
vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end)
vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end)
vim.keymap.set("n", "<leader>vws", function() vim.lsp.buf.workspace_symbol() end)
vim.keymap.set("n", "<leader>vd", function() vim.diagnostic.setloclist() end)
vim.keymap.set("n", "[d", function() vim.diagnostic.goto_next() end)
vim.keymap.set("n", "]d", function() vim.diagnostic.goto_prev() end)
vim.keymap.set("n", "<leader>vca", function() vim.lsp.buf.code_action() end)
vim.keymap.set("n", "<leader>vrn", function() vim.lsp.buf.rename() end)
vim.keymap.set("n", "<leader>ls", function() vim.lsp.buf.signature_help() end)
vim.keymap.set('n', '<C-k>i', "<cmd>lua vim.diagnostic.open_float()<CR>")
vim.keymap.set("n", "<leader>f", function() vim.lsp.buf.format() end)
